language: node_js
node_js:
  - "4.1"
  - "4.0"
before_script:
  - npm install -g gulp
script: gulp test

# whitelist
branches:
  only:
    - master
    - development

notifications:
  email: false
  slack: vacmatch:61qt7wMKuO0e8juiX6MCnX6T
